bgm_schedules: []
schedules:
- announcement: general/opening
  bgm_action: play
  days:
  - monday
  - tuesday
  - wednesday
  - thursday
  - friday
  label: 개장 안내
  time: 06:00
- announcement: safety/general_safety
  days:
  - monday
  - tuesday
  - wednesday
  - thursday
  - friday
  label: 안전 수칙 안내
  time: 09:00
- announcement: safety/sanitize
  days:
  - monday
  - tuesday
  - wednesday
  - thursday
  - friday
  label: 기구 소독 안내
  time: '17:00'
- announcement: general/opening
  days:
  - monday
  - tuesday
  - wednesday
  - thursday
  - friday
  label: 개장 안내
  time: '17:55'
- announcement: general/closing_warning
  days:
  - saturday
  label: 마감 30분전 안내
  time: '18:30'
- announcement: general/opening
  days:
  - saturday
  label: 개장 안내
  time: '18:50'
- announcement: general/closing
  bgm_action: stop
  days:
  - saturday
  label: 마감 안내
  time: '18:50'
